### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by sveba** [kubeops/config-syncer#466]
Hi guys, 
Thank you for this great project. Can you share some information about the release cycle? The last release was 9 months ago and since then there have been some code changes, which are meaningful.

Thank you

**Comment by larssb** [comment]
So anyone from AppsCode ... what's your take on this?

**Comment by sveba** [comment]
> So anyone from AppsCode ... what's your take on this?

I already switched to more reliable project: https://github.com/mittwald/kubernetes-replicator

**Comment by tamalsaha** [comment]
https://github.com/kubeops/config-syncer/releases/tag/v0.13.0
