### ISSUE TITLE
sync rolebindings feature?

### ISSUE THREAD

**Issue by efossas** [kubeops/config-syncer#485]
Is there any interest in extending this app to sync rolebindings? 

My use case is that I have rolebindings that I apply to many namespaces, but not all of them (i use a clusterrole in the rolebindings). Kubed's ability to sync a resource to namespaces by label-selector would be really useful for me.

I could contribute the code as well, but just want to make sure this is something that is wanted before I code it up.

**Comment by sathieu** [comment]
This project does: https://github.com/mittwald/kubernetes-replicator

**Comment by efossas** [comment]
Works for me, thanks for the suggestion
