### ISSUE TITLE
e2e tests failures

### ISSUE THREAD

**Issue by palassis-8451** [kubeops/config-syncer#498]
Hello,
It seems like e2e tests are failing and have been failing for a long time.  Looking at a few of the logs, a common error seen has to do with flags for ginkgo (https://github.com/kubeops/config-syncer/runs/4229018595?check_suite_focus=true#step:6:91).  Is it possible [this](https://github.com/kubeops/config-syncer/blob/master/test/e2e/option_test.go#L61) needs to be modified to remove the "-logtostderr" flag since it seems it is no longer an option per the [ginkgo documentation](https://onsi.github.io/ginkgo/#running-tests).

Thanks!

**Comment by tamalsaha** [comment]
Fixed https://github.com/kubeops/config-syncer/commit/54b0a53233e74565a6f3aade54b9abf3fecfe75f
