### ISSUE TITLE
kubed v0.12.0 image is not available

### ISSUE THREAD

**Issue by kozart** [kubeops/config-syncer#539]
Looks like latest pushes to the dockerhub removed kubed:v0.12.0 tag

Reproduce:
```
docker pull appscode/kubed:v0.12.0
v0.12.0: Pulling from appscode/kubed
00411772422b: Pulling fs layer
invalid rootfs in image configuration
```

**Comment by hpsony94** [comment]
![image](https://user-images.githubusercontent.com/16579599/210330158-ca383973-d94b-47d7-9af9-0b6f6d41e552.png)
I guess they just introduced a breaking change that can break the old running deployment from our side as well.
I just got the failed deployment today, and realized that they changed the metadata of docker image v0.12.0

**Comment by hpsony94** [comment]
Hopefully, I did a workaround from my side to use another arch docker image with the same version.
```
➜  ~ docker pull appscode/kubed:v0.12.0_linux_amd64                                                                                                             <aws:employmenthero-ops-stg>
v0.12.0_linux_amd64: Pulling from appscode/kubed
9ff2acc3204b: Pull complete
dca1a2f6180a: Pull complete
Digest: sha256:5e9091f069d6fb808d0c229e81ffd65f0283851c859dfe5c48e39b3a6d0f6569
Status: Downloaded newer image for appscode/kubed:v0.12.0_linux_amd64
docker.io/appscode/kubed:v0.12.0_linux_amd64
```

**Comment by mleklund** [comment]
retagging images is just bad form.

**Comment by ahalay** [comment]
> Fortunately, I did a workaround from my side to use another arch docker image with the same version.
> 
> ```
> ➜  ~ docker pull appscode/kubed:v0.12.0_linux_amd64                                                                                                             <aws:employmenthero-ops-stg>
> v0.12.0_linux_amd64: Pulling from appscode/kubed
> 9ff2acc3204b: Pull complete
> dca1a2f6180a: Pull complete
> Digest: sha256:5e9091f069d6fb808d0c229e81ffd65f0283851c859dfe5c48e39b3a6d0f6569
> Status: Downloaded newer image for appscode/kubed:v0.12.0_linux_amd64
> docker.io/appscode/kubed:v0.12.0_linux_amd64
> ```

If you have a helm chart it could be fixed by changing `operator.tag` value from `v0.12.0` to `v0.12.0@sha256:5e9091f069d6fb808d0c229e81ffd65f0283851c859dfe5c48e39b3a6d0f6569` so it will not be affected if `v0.12.0_linux_amd64` will also be retagged by using hash instead

**Comment by donbowman** [comment]
No comment from anyone? the images have been changed (and are no longer same format).
Did the project lose control of their docker credentials?
https://hub.docker.com/u/1gtm 
updated all the images https://hub.docker.com/r/appscode/kubed/tags
changing them to type 'helm'.

**Comment by mleklund** [comment]
I concur @donbowman, my response has been to uninstall kubed/config-syncer.  While it is a bit of a pain, I can use kustomize to install it wherever I need it.

**Comment by ceilingfish** [comment]
This looks very much like a supply chain attack (albeit a clumsy one). Going to have to move away from kubed now, which is vexing.

**Comment by JeremJR** [comment]
@tamalsaha sorry to bother you. I'm also an happy user of kubed and I wonder what cause this breaking change. It seems that helm charts have been pushed using the same tags than previous docker images. Do you have details on that? Could it be reverted? Could we help somehow?

**Comment by donbowman** [comment]
i think at this stage this is a pretty severe security breakdown.

Is there any controls so that the developer who builds something cannot push?
is multi-factor used on that end?

the project has no security policy.

e.g. here it might be benign, but its not safe to assume so.

the containers are build not from the CI, so taht is another redflag.

**Comment by tamalsaha** [comment]
I have published v0.14.0-rc.0 version which used ghcr.io/appscode as the Docker registry by default. Let me know if that fixes the issue.

https://github.com/kubeops/config-syncer/actions/runs/3900336546

**Comment by JeremJR** [comment]
Thank you @tamalsaha it's working with the latest stable v0.13.2
By the way, the documentation is still mentioning v0.12.0 as latest version.
![kubed_doc](https://user-images.githubusercontent.com/1147953/212182560-97180526-efa0-49ea-ba0b-32f69339d06d.png)

**Comment by xrl** [comment]
`0.12.0` should have been re-released and fixed. It's fine to make a mistake and improve process, but now the app is broken for users. This has reputational harm.

**Comment by tamalsaha** [comment]
I have pushed the v0.12.0 image again. This is the GH workflow run: https://github.com/kubeops/config-syncer/actions/runs/4066827902

Please comment/reopen if there are still remaining issues.
